### ISSUE TITLE
[BUG] - Cannot replicate the results from example - Fitting all available distributions to data

### ISSUE THREAD

**Issue by issacwu2** [MatthewReid854/reliability#27]
**Describe the bug**
When I try to replicate the result from example 2 in "Fitting all available distributions to data", error is prompted.

**To Reproduce**
code:
```
from reliability.Fitters import Fit_Everything
from reliability.Distributions import Weibull_Distribution
from reliability.Other_functions import make_right_censored_data

raw_data = Weibull_Distribution(alpha=12, beta=3).random_samples(100, seed=2)  # create some data
data = make_right_censored_data(raw_data, threshold=14)  # right censor the data
results = Fit_Everything(failures=data.failures, right_censored=data.right_censored)  # fit all the models
print('The best fitting distribution was', results.best_distribution_name, 'which had parameters', results.best_distribution.parameters)
```

output:
```
Results from Fit_Everything:
Analysis method: MLE
Failures / Right censored: 86/14 (14.0% right censored) 

    Distribution   Alpha    Beta   Gamma Alpha 1  Beta 1 Alpha 2  Beta 2 Proportion 1       DS      Mu    Sigma    Lambda  Log-likelihood    AICc     BIC      AD optimizer
      Weibull_2P 11.2773 3.30301                                                                                                 -241.959 488.041 493.128  44.945       TNC
       Normal_2P                                                                               10.1194  3.37466                  -242.479 489.082 494.169 44.9098       TNC
        Gamma_2P 1.42301 7.21417                                                                                                 -243.235 490.594  495.68 45.2817       TNC
  Loglogistic_2P 9.86245 4.48433                                                                                                 -243.588 491.301 496.387 45.2002       TNC
      Weibull_DS 10.7383 3.57496                                                      0.930423                                   -241.594 489.437 497.003 44.9447       TNC
      Weibull_3P 10.0786 2.85821 1.15092                                                                                         -241.779 489.807 497.373 44.9927       TNC
 Weibull_Mixture                         3.59763  113.23 11.4208 3.54075    0.0276899                                            -237.392 485.421 497.809 44.9283       TNC
        Gamma_3P 1.42301 7.21417       0                                                                                         -243.235  492.72 500.286 45.2817  L-BFGS-B
    Lognormal_2P                                                                               2.26524 0.406436                  -245.785 495.694  500.78 45.6874       TNC
  Loglogistic_3P 9.86245 4.48433       0                                                                                         -243.588 493.427 500.992 45.2002       TNC
      Weibull_CR                         11.4119 3.30302  30.253 3.30282                                                         -241.959 492.338 502.338  44.945       TNC
    Lognormal_3P                       0                                                       2.26524 0.406436                  -245.785  497.82 505.385 45.6874       TNC
       Gumbel_2P                                                                               11.5926  2.94944                  -248.348 500.819 505.906 45.4624  L-BFGS-B
  Exponential_2P                 2.82892                                                                         0.121884        -267.003 538.129 543.216 51.7852       TNC
  Exponential_1P                                                                                                0.0870024        -295.996 594.034 596.598 56.8662       TNC 

Traceback (most recent call last):
  File "C:/Users/issac/iCloudDrive/Coding Projects/pythonProject/testing.py", line 7, in <module>
    results = Fit_Everything(failures=data.failures, right_censored=data.right_censored)  # fit all the models
  File "C:\Users\issac\iCloudDrive\Coding Projects\pythonProject\venv\lib\site-packages\reliability\Fitters.py", line 1255, in __init__
    Fit_Everything.__histogram_plot(self)
  File "C:\Users\issac\iCloudDrive\Coding Projects\pythonProject\venv\lib\site-packages\reliability\Fitters.py", line 1497, in __histogram_plot
    self.__Weibull_2P_params.distribution.CDF(CI=False, linestyle=ls)
  File "C:\Users\issac\iCloudDrive\Coding Projects\pythonProject\venv\lib\site-packages\reliability\Distributions.py", line 508, in CDF
    self, "CDF", xvals, xmin, xmax, show_plot, plot_CI, CI_type, CI, CI_y, CI_x
  File "C:\Users\issac\iCloudDrive\Coding Projects\pythonProject\venv\lib\site-packages\reliability\Utils.py", line 7069, in distributions_input_checking
    "CI must be between 0 and 1. Default is 0.95 for 95% confidence interval. Only used if the distribution object was created by Fitters."
ValueError: CI must be between 0 and 1. Default is 0.95 for 95% confidence interval. Only used if the distribution object was created by Fitters.

Process finished with exit code 1


```

**Comment by MatthewReid854** [comment]
Thanks for identifying this bug.
It is now fixed with the release of v0.8.1.
